# Generated by Django 4.1.4 on 2022-12-13 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.BigIntegerField()),
                ('number', models.BigIntegerField()),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 6, 12, 9, 8, 48, 625252))),
                ('date_use', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('not active', 'не активирована'), ('active', 'активирована'), ('expired', 'просрочена')], max_length=50)),
            ],
        ),
    ]
